version: "3.9"

services:
  postgres:
    image: postgres:14.1
    container_name: daily-diet-postgres
    volumes:
      - "postgres:/var/lib/postgresql/data/"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRESS_DB: default_database

volumes:
  postgres:
